env: "local"

storage_path: "./storage/storage.db"

http_server:
  address: "localhost: 8080"

db: "host=localhost user=admin password=myPassword dbname=postgres port=5432 sslmode=disable TimeZone=Europe/Moscow"
